version: '3.8'
services:
  redis:
    image: redis:7.0.0-alpine
    ports:
      - "6379:6379"
    env_file:
      - .env
  rest:
    build:
      context: .
      target: rest
    ports:
      - "1235:1235"
    depends_on:
      - redis
    env_file:
      - .env
  gateway:
    build:
      context: .
      target: gateway
    depends_on:
      - rest
      - bot
    env_file:
      - .env
  gateway2:
    build:
      context: .
      target: gateway
    depends_on:
      - rest
      - bot
    env_file:
      - .env
  bot:
    build:
      context: .
      target: bot
    depends_on:
      - rest
    env_file:
      - .env
  rabbitmq:
    build:
      context: .
      target: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"